#object files, directories for current project
OBJS=fooMain.o
ARCHS=../../ALib/libfoo.a ../../ALib/libone.a
DIRS=.. ../../One

#executable name
EXEFILE=../../ABin/foo

#all other makefile lines
include ../../makecommonstest
