#object files for current project
OBJS=TreeGeneric.o TreeGenericTest.o TreeGenericMain.o LListGenFunc.o GenericStack.o

#executable name
EXEFILE=tree

#all other makefile lines
include ../../makecommons
