#object files, directories for this test
OBJS=HeapGenericTest.o HeapGenericMain.o
LIBS=../../ALib/libheap.a ../../ALib/libvector.a
DIRS=.. ../../Vector

#executable name
EXEFILE=../../ABin/heap

#all other makefile lines
include ../../maketests
